# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_application.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontal_label = QtWidgets.QHBoxLayout()
        self.horizontal_label.setContentsMargins(-1, 1, -1, -1)
        self.horizontal_label.setSpacing(15)
        self.horizontal_label.setObjectName("horizontal_label")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_label.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontal_label.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontal_label.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontal_label.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontal_label.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontal_label.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_label.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontal_label)
        self.horizontal_filter = QtWidgets.QHBoxLayout()
        self.horizontal_filter.setContentsMargins(-1, -1, -1, 10)
        self.horizontal_filter.setSpacing(15)
        self.horizontal_filter.setObjectName("horizontal_filter")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_filter.addItem(spacerItem2)
        self.tratta_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.tratta_combobox.setObjectName("tratta_combobox")
        self.horizontal_filter.addWidget(self.tratta_combobox)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.listWidget.setObjectName("listWidget")
        self.horizontal_filter.addWidget(self.listWidget)
        self.data_partenza_selector = QtWidgets.QDateEdit(self.centralwidget)
        self.data_partenza_selector.setObjectName("data_partenza_selector")
        self.horizontal_filter.addWidget(self.data_partenza_selector)
        self.data_arrivo_selector = QtWidgets.QDateEdit(self.centralwidget)
        self.data_arrivo_selector.setObjectName("data_arrivo_selector")
        self.horizontal_filter.addWidget(self.data_arrivo_selector)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox.setStyleSheet("QCheckBox::indicator {\n"
"     width: 20px;\n"
"     height: 20px;\n"
"}")
        self.checkBox.setText("")
        self.checkBox.setIconSize(QtCore.QSize(42, 44))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontal_filter.addWidget(self.checkBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_filter.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontal_filter)
        self.horizontalButton = QtWidgets.QHBoxLayout()
        self.horizontalButton.setObjectName("horizontalButton")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalButton.addItem(spacerItem4)
        self.create_graphics = QtWidgets.QPushButton(self.centralwidget)
        self.create_graphics.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.create_graphics.setObjectName("create_graphics")
        self.horizontalButton.addWidget(self.create_graphics)
        self.clear_filter = QtWidgets.QPushButton(self.centralwidget)
        self.clear_filter.setObjectName("clear_filter")
        self.horizontalButton.addWidget(self.clear_filter)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalButton.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalButton)
        self.top_separator_layout = QtWidgets.QHBoxLayout()
        self.top_separator_layout.setContentsMargins(-1, -1, -1, 5)
        self.top_separator_layout.setObjectName("top_separator_layout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.top_separator_layout.addItem(spacerItem6)
        self.top_separator_line = QtWidgets.QFrame(self.centralwidget)
        self.top_separator_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.top_separator_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.top_separator_line.setObjectName("top_separator_line")
        self.top_separator_layout.addWidget(self.top_separator_line)
        spacerItem7 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.top_separator_layout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.top_separator_layout)
        self.statistics_image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statistics_image.sizePolicy().hasHeightForWidth())
        self.statistics_image.setSizePolicy(sizePolicy)
        self.statistics_image.setAutoFillBackground(False)
        self.statistics_image.setText("")
        self.statistics_image.setPixmap(QtGui.QPixmap("assets/app_images/placeholder.jpg"))
        self.statistics_image.setAlignment(QtCore.Qt.AlignCenter)
        self.statistics_image.setObjectName("statistics_image")
        self.verticalLayout.addWidget(self.statistics_image)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        self.spinner_vertical_layout = QtWidgets.QVBoxLayout()
        self.spinner_vertical_layout.setObjectName("spinner_vertical_layout")
        self.verticalLayout.addLayout(self.spinner_vertical_layout)
        self.bottom_separator_line = QtWidgets.QFrame(self.centralwidget)
        self.bottom_separator_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.bottom_separator_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bottom_separator_line.setObjectName("bottom_separator_line")
        self.verticalLayout.addWidget(self.bottom_separator_line)
        spacerItem9 = QtWidgets.QSpacerItem(20, 71, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.footer_layout = QtWidgets.QHBoxLayout()
        self.footer_layout.setContentsMargins(-1, -1, -1, 5)
        self.footer_layout.setSpacing(6)
        self.footer_layout.setObjectName("footer_layout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footer_layout.addItem(spacerItem10)
        self.label_product_by = QtWidgets.QLabel(self.centralwidget)
        self.label_product_by.setObjectName("label_product_by")
        self.footer_layout.addWidget(self.label_product_by)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.footer_layout.addItem(spacerItem11)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.footer_layout.addWidget(self.label_5)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.footer_layout.addItem(spacerItem12)
        self.label_version = QtWidgets.QLabel(self.centralwidget)
        self.label_version.setObjectName("label_version")
        self.footer_layout.addWidget(self.label_version)
        self.verticalLayout.addLayout(self.footer_layout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Siremar Analitycs"))
        self.label_2.setText(_translate("MainWindow", "Tratta"))
        self.label_3.setText(_translate("MainWindow", "Nave"))
        self.label_4.setText(_translate("MainWindow", "Intervallo data partenza"))
        self.label.setText(_translate("MainWindow", "Intervallo data arrivo"))
        self.label_6.setText(_translate("MainWindow", "Anno"))
        self.create_graphics.setText(_translate("MainWindow", "Genera grafico"))
        self.clear_filter.setText(_translate("MainWindow", "Azzera filtri"))
        self.label_product_by.setText(_translate("MainWindow", "Copyright Simone Condorelli"))
        self.label_5.setText(_translate("MainWindow", "Version :"))
        self.label_version.setText(_translate("MainWindow", "0.0.1"))
