DFS_ROOT = "hdfs://localhost:9000/"
PARQUET_FILE_CARGO = DFS_ROOT + "tesi_siremar/siremar_cargo.parquet"
PARQUET_FILE_PRENOTATION = DFS_ROOT + "tesi_siremar/siremar_prenotation.parquet"
ASSETS = "./assets/"
WINDOW_WIDTH = 1800
WINDOW_HEIGHT = 1080
IMAGE_WIDTH = 1680
VERSION = "0.0.1"
APP_TITLE = "Siremar Cargo analysis"
PLACEHOLDER_PATH = "./assets/app_images/placeholder.jpg"
TEMP_IMAGE_STATISTICS = "./assets/app_images/statistics.jpg"