DFS_ROOT = "hdfs://localhost:9000/"
PARQUET_FILE_CARGO = DFS_ROOT + "tesi_siremar/siremar_cargo.parquet"
PARQUET_FILE_PRENOTATION = DFS_ROOT + "tesi_siremar/siremar_prenotation.parquet"
ASSETS = "./assets/"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 800
IMAGE_HEIGHT = 480
APP_TITLE = "Siremar Cargo analysis"
PLACEHOLDER_PATH = "./assets/app_images/placeholder.jpg"